[package]
name = "findomain"
version = "2.1.4"
authors = ["Eduard Tolosa <edu4rdshl@protonmail.com>"]
edition = "2018"
description = "The fastest and cross-platform subdomain enumerator, do not waste your time."
repository = "https://github.com/edu4rdshl/findomain"
license = "GPL-3.0-or-later"
keywords = ["discover-subdomains", "ct-logs", "search-subdomains", "enumerate-subdomains", "subdomain-scanner"]
readme = "README.md"

[dependencies]
serde = { version = "1.0.115", features = ["derive"] }
serde_derive = "1.0.115"
reqwest = { version = "0.10.8", features = ["blocking", "json"] }
trust-dns-resolver = { version = "0.19.5", features = ["dns-over-rustls"] }
clap = { version = "2.33.3", features = ["yaml"] }
lazy_static = "1.4.0"
rand = "0.7.3"
postgres = "0.17.5"
failure = "0.1.8"
rayon = "1.4.0"
semver = "0.10.0"
url = "2.1.1"
config = { version = "0.10.1", features = ["yaml", "json", "toml", "hjson", "ini"] }

[target.arm-unknown-linux-gnueabihf.dependencies]
openssl = { version = "0.10.30", features = ["vendored"] }

[target.aarch64-unknown-linux-gnu.dependencies]
openssl = { version = "0.10.30", features = ["vendored"] }
